project:
  type: book
  output-dir: docs

lang: fr

book:
  title: "Statistiques Fondamentales"
  author: "Simon Coste"
  date: today
  chapters:
    - index.qmd
    - ch1.qmd
    - ch2.qmd
    - ch3.qmd
    - ch4.qmd
    - ch5.qmd 
    - ch6.qmd
    - ch7.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: simplex
      dark: solar

  pdf:
    documentclass: scrreport

jupyter: julia-1.9