project:
  type: book
  output-dir: docs

lang: fr

book:
  title: "Statistiques Fondamentales"
  author: "Simon Coste"
  date: today
  repo-url: "https://github.com/statsfonda/site"
  downloads: pdf
  chapters:
    - index.qmd
    - ch1.qmd
    - ch2.qmd
    - ch2_1.qmd
    - ch2_ex.qmd
    - ch3.qmd
    - ch31_outils.qmd
    - ch3_ex.qmd
    - ch4_0.qmd
    - ch4_1.qmd
    - ch4_2.qmd
    - ch4_ex.qmd
    - ch5_0.qmd 
    - ch5_01.qmd
    - ch5_1.qmd
    - ch5_2.qmd
    - ch5_ex.qmd
    - ch6_0.qmd
    - ch6_1.qmd
    - ch6_2.qmd
    - ch7.qmd
    - references.qmd
    - ref.qmd
    - app1.qmd
  sidebar:
    style: docked
    logo: "images/logoUP.png"

bibliography: references.bib

format:
  html:
    mainfont: "Computer Modern Serif"
    theme:
      light: simplex
      dark: solar
    css: styles.css
    include-before-body:
      - macros



  pdf:
    documentclass: scrreport
    fontsize: "10"
    margin-left: 2cm
    margin-right: 2cm
    margin-bottom: 3cm
    margin-top: 2cm
    include-in-header:
      - macros.tex
    


jupyter: julia-1.9