project:
  type: book
  output-dir: docs

lang: fr

book:
  title: "Statistiques Fondamentales"
  author: "Simon Coste"
  date: today
  repo-url: "https://github.com/statsfonda/site"
  downloads: pdf
  chapters:
    - index.qmd
    - ch1.qmd
    - ch2.qmd
    - ch2_ex.qmd
    - ch3.qmd
    - ch31_outils.qmd
    - ch3_ex.qmd
    - ch4.qmd
    - ch5.qmd 
    - ch6.qmd
    - ch7.qmd
    - references.qmd
  sidebar:
    style: docked
    logo: "images/logoUP.png"

bibliography: references.bib

format:
  html:
    mainfont: "Computer Modern Serif"
    theme:
      light: simplex
      dark: solar
    css: styles.css

  pdf:
    documentclass: scrreport
    fontsize: "10"
    margin-left: 2cm
    margin-right: 2cm
    margin-bottom: 3cm
    margin-top: 2cm

jupyter: julia-1.9